// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from './routes/_404.tsx';
import * as $api_auth_magic_link from './routes/api/auth/magic-link.ts';
import * as $api_gate_submit from './routes/api/gate-submit.ts';
import * as $api_gate from './routes/api/gate.ts';
import * as $api_health from './routes/api/health.ts';
import * as $api_metrics from './routes/api/metrics.ts';
import * as $api_newsletter_confirm from './routes/api/newsletter/confirm.ts';
import * as $api_newsletter_subscribe from './routes/api/newsletter/subscribe.ts';
import * as $api_newsletter_unsubscribe from './routes/api/newsletter/unsubscribe.ts';
import * as $api_questions_answer from './routes/api/questions/answer.ts';
import * as $api_questions_next from './routes/api/questions/next.ts';
import * as $api_lotto_close from './routes/api/lotto/close.ts';
import * as $api_lotto_commit from './routes/api/lotto/commit.ts';
import * as $api_lotto_draw from './routes/api/lotto/draw.ts';
import * as $api_lotto_verify from './routes/api/lotto/verify.ts';
import * as $api_responses from './routes/api/responses.ts';
import * as $auth_verify from './routes/auth/verify.tsx';
import * as $encrypted_messenger from './routes/encrypted-messenger.tsx';
import * as $gate from './routes/gate.tsx';
import * as $index from './routes/index.tsx';
import * as $login from './routes/login.tsx';
import * as $lotto from './routes/lotto.tsx';
import * as $messenger from './routes/messenger.tsx';
import * as $questionnaire from './routes/questionnaire.tsx';
import * as $questions from './routes/questions.tsx';
import * as $GateQuestionnaire from './islands/GateQuestionnaire.tsx';
import * as $QuaternarySpheroid from './islands/QuaternarySpheroid.tsx';
import type { Manifest } from '$fresh/server.ts';

const manifest = {
  routes: {
    './routes/_404.tsx': $_404,
    './routes/api/auth/magic-link.ts': $api_auth_magic_link,
    './routes/api/gate-submit.ts': $api_gate_submit,
    './routes/api/gate.ts': $api_gate,
    './routes/api/health.ts': $api_health,
    './routes/api/metrics.ts': $api_metrics,
    './routes/api/newsletter/confirm.ts': $api_newsletter_confirm,
    './routes/api/newsletter/subscribe.ts': $api_newsletter_subscribe,
    './routes/api/newsletter/unsubscribe.ts': $api_newsletter_unsubscribe,
    './routes/api/questions/answer.ts': $api_questions_answer,
    './routes/api/questions/next.ts': $api_questions_next,
    './routes/api/lotto/close.ts': $api_lotto_close,
    './routes/api/lotto/commit.ts': $api_lotto_commit,
    './routes/api/lotto/draw.ts': $api_lotto_draw,
    './routes/api/lotto/verify.ts': $api_lotto_verify,
    './routes/api/responses.ts': $api_responses,
    './routes/auth/verify.tsx': $auth_verify,
    './routes/encrypted-messenger.tsx': $encrypted_messenger,
    './routes/gate.tsx': $gate,
    './routes/index.tsx': $index,
    './routes/login.tsx': $login,
    './routes/lotto.tsx': $lotto,
    './routes/messenger.tsx': $messenger,
    './routes/questionnaire.tsx': $questionnaire,
    './routes/questions.tsx': $questions,
  },
  islands: {
    './islands/GateQuestionnaire.tsx': $GateQuestionnaire,
    './islands/QuaternarySpheroid.tsx': $QuaternarySpheroid,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
