// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from './routes/_404.tsx';
import * as $api_auth_magic_link from './routes/api/auth/magic-link.ts';
import * as $api_gate_submit from './routes/api/gate-submit.ts';
import * as $api_gate from './routes/api/gate.ts';
import * as $api_health from './routes/api/health.ts';
import * as $api_metrics from './routes/api/metrics.ts';
import * as $api_questions_answer from './routes/api/questions/answer.ts';
import * as $api_questions_next from './routes/api/questions/next.ts';
import * as $api_responses from './routes/api/responses.ts';
import * as $auth_verify from './routes/auth/verify.tsx';
import * as $completion from './routes/completion.tsx';
import * as $gate from './routes/gate.tsx';
import * as $index from './routes/index.tsx';
import * as $login from './routes/login.tsx';
import * as $questionnaire from './routes/questionnaire.tsx';
import * as $GateQuestionnaire from './islands/GateQuestionnaire.tsx';
import type { Manifest } from '$fresh/server.ts';

const manifest = {
  routes: {
    './routes/_404.tsx': $_404,
    './routes/api/auth/magic-link.ts': $api_auth_magic_link,
    './routes/api/gate-submit.ts': $api_gate_submit,
    './routes/api/gate.ts': $api_gate,
    './routes/api/health.ts': $api_health,
    './routes/api/metrics.ts': $api_metrics,
    './routes/api/questions/answer.ts': $api_questions_answer,
    './routes/api/questions/next.ts': $api_questions_next,
    './routes/api/responses.ts': $api_responses,
    './routes/auth/verify.tsx': $auth_verify,
    './routes/completion.tsx': $completion,
    './routes/gate.tsx': $gate,
    './routes/index.tsx': $index,
    './routes/login.tsx': $login,
    './routes/questionnaire.tsx': $questionnaire,
  },
  islands: {
    './islands/GateQuestionnaire.tsx': $GateQuestionnaire,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
