/**
 * Tests for the generated fresh.gen.ts manifest
 *
 * This file is auto-generated by Fresh, but is checked into source control.
 * This PR added the new `./routes/questions.tsx` route and the new
 * `./islands/QuaternarySpheroid.tsx` island to the manifest. These tests
 * guard against the manifest and the actual filesystem modules drifting
 * apart (e.g. a route/island added to the folder but never wired into the
 * manifest, or vice versa).
 *
 * Run with: deno task test
 */

import { assertEquals, assertExists, assertStringIncludes } from '$std/assert/mod.ts';
import manifest from '../fresh.gen.ts';
import * as questionsRouteModule from '../routes/questions.tsx';
import * as indexRouteModule from '../routes/index.tsx';
import * as quaternarySpheroidModule from '../islands/QuaternarySpheroid.tsx';
import * as gateQuestionnaireModule from '../islands/GateQuestionnaire.tsx';

Deno.test({
  name: 'fresh.gen.ts - registers the new questions route under its file path key',
  fn() {
    assertExists(manifest.routes['./routes/questions.tsx']);
    assertEquals(manifest.routes['./routes/questions.tsx'], questionsRouteModule);
  },
});

Deno.test({
  name: 'fresh.gen.ts - registers the new QuaternarySpheroid island under its file path key',
  fn() {
    assertExists(manifest.islands['./islands/QuaternarySpheroid.tsx']);
    assertEquals(manifest.islands['./islands/QuaternarySpheroid.tsx'], quaternarySpheroidModule);
  },
});

Deno.test({
  name: 'fresh.gen.ts - does not remove pre-existing routes/islands',
  fn() {
    assertEquals(manifest.routes['./routes/index.tsx'], indexRouteModule);
    assertEquals(manifest.islands['./islands/GateQuestionnaire.tsx'], gateQuestionnaireModule);
  },
});

Deno.test({
  name: 'fresh.gen.ts - registered questions route exposes a GET handler',
  fn() {
    const registered = manifest.routes['./routes/questions.tsx'];
    assertExists(registered.handler);
    assertEquals(typeof registered.handler.GET, 'function');
  },
});

Deno.test({
  name: 'fresh.gen.ts - registered QuaternarySpheroid island exposes a default component export',
  fn() {
    const registered = manifest.islands['./islands/QuaternarySpheroid.tsx'];
    assertEquals(typeof registered.default, 'function');
    assertEquals(registered.default.name, 'QuaternarySpheroid');
  },
});

Deno.test({
  name: 'fresh.gen.ts - routes and islands maps contain exactly the expected keys',
  fn() {
    assertEquals(Object.keys(manifest.routes).sort(), [
      './routes/_404.tsx',
      './routes/api/auth/magic-link.ts',
      './routes/api/gate-submit.ts',
      './routes/api/gate.ts',
      './routes/api/health.ts',
      './routes/api/metrics.ts',
      './routes/api/newsletter/confirm.ts',
      './routes/api/newsletter/subscribe.ts',
      './routes/api/newsletter/unsubscribe.ts',
      './routes/api/questions/answer.ts',
      './routes/api/questions/next.ts',
      './routes/api/responses.ts',
      './routes/auth/verify.tsx',
      './routes/gate.tsx',
      './routes/index.tsx',
      './routes/login.tsx',
      './routes/questionnaire.tsx',
      './routes/questions.tsx',
    ].sort());

    assertEquals(Object.keys(manifest.islands).sort(), [
      './islands/GateQuestionnaire.tsx',
      './islands/QuaternarySpheroid.tsx',
    ].sort());
  },
});

Deno.test({
  name: 'fresh.gen.ts - baseUrl points at this manifest file',
  fn() {
    assertEquals(typeof manifest.baseUrl, 'string');
    assertStringIncludes(manifest.baseUrl, 'fresh.gen.ts');
  },
});