import React, { useState } from 'react';

// --- SVG Icons ---
const MailIcon=()=>(<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M4 4h16c1.1 0 2 .9 2 2v12c0 1.1-.9 2-2 2H4c-1.1 0-2-.9-2-2V6c0-1.1.9-2 2-2z"></path><polyline points="22,6 12,13 2,6"></polyline></svg>);
const GithubIcon=()=>(<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M9 19c-5 1.5-5-2.5-7-3m14 6v-3.87a3.37 3.37 0 0 0-.94-2.61c3.14-.35 6.44-1.54 6.44-7A5.44 5.44 0 0 0 20 4.77 5.07 5.07 0 0 0 19.91 1S18.73.65 16 2.48a13.38 13.38 0 0 0-7 0C6.27.65 5.09 1 5.09 1A5.07 5.07 0 0 0 5 4.77a5.44 5.44 0 0 0-1.5 3.78c0 5.42 3.3 6.61 6.44 7A3.37 3.37 0 0 0 9 18.13V22"></path></svg>);

// --- Styles ---
const styles:{[key:string]: React.CSSProperties} = {container:{maxWidth:'750px',margin:'40px auto',padding:'0 20px',lineHeight:'1.7',color:'#ccc',fontFamily:'sans-serif'},header:{textAlign:'center',borderBottom:'1px solid #333',paddingBottom:'20px',marginBottom:'30px'},title:{fontSize:'2.5rem',color:'#fff',fontWeight:300},subtitle:{fontSize:'1rem',color:'#888',fontStyle:'italic'},contactSection:{display:'flex',flexDirection:'column',alignItems:'center',gap:'20px',marginBottom:'40px'},contactLink:{display:'flex',alignItems:'center',gap:'10px',color:'#ccc',textDecoration:'none',fontSize:'1.1rem',transition:'color 0.2s ease-in-out'},keyContainer:{marginTop:'50px'},keyTitle:{fontSize:'1.5rem',color:'#fff',fontWeight:300,marginBottom:'10px',textAlign:'center'},keyBlock:{backgroundColor:'#1a1a1a',border:'1px solid #333',padding:'15px',borderRadius:'8px',whiteSpace:'pre-wrap',wordBreak:'break-all',color:'#999',fontFamily:'monospace',maxHeight:'200px',overflowY:'auto'},copyButtonContainer:{display:'flex',justifyContent:'center',marginTop:'15px'},copyButton:{backgroundColor:'#003333',color:'#00ffff',border:'1px solid #00ffff',padding:'10px 20px',borderRadius:'5px',cursor:'pointer',fontSize:'1rem',transition:'background-color 0.2s, color 0.2s'}};

const pgpPublicKey=`-----BEGIN PGP PUBLIC KEY BLOCK-----\n\nmQINBGPq1asBEADL7qg... (your key data here) ...R9g3C4j/w==\n=ABC1\n-----END PGP PUBLIC KEY BLOCK-----`;

export default function ContactPage() {
    const[copyButtonText,setCopyButtonText]=useState('Copy Key');
    const handleCopy=()=>{const textArea=document.createElement('textarea');textArea.value=pgpPublicKey;textArea.style.position='fixed';document.body.appendChild(textArea);textArea.focus();textArea.select();try{document.execCommand('copy');setCopyButtonText('Copied!');setTimeout(()=>setCopyButtonText('Copy Key'),2000);}catch(err){console.error('Failed to copy text: ',err);setCopyButtonText('Failed!');setTimeout(()=>setCopyButtonText('Copy Key'),2000);}document.body.removeChild(textArea);};
    const handleHover=(e: React.MouseEvent<HTMLAnchorElement>,enter: boolean)=>{e.currentTarget.style.color=enter?'#00ffff':'#ccc';};
    
    return(<div style={styles.container}><header style={styles.header}><h1 style={styles.title}>Contact</h1><p style={styles.subtitle}>Get in touch or send an encrypted message.</p></header><div style={styles.contactSection}><a href="mailto:your-email@example.com" style={styles.contactLink} onMouseEnter={(e)=>handleHover(e,true)} onMouseLeave={(e)=>handleHover(e,false)}><MailIcon/> your-email@example.com</a><a href="https://linkedin.com/in/your-profile" target="_blank" rel="noopener noreferrer" style={styles.contactLink} onMouseEnter={(e)=>handleHover(e,true)} onMouseLeave={(e)=>handleHover(e,false)}><LinkedinIcon/> LinkedIn Profile</a><a href="https://github.com/your-username" target="_blank" rel="noopener noreferrer" style={styles.contactLink} onMouseEnter={(e)=>handleHover(e,true)} onMouseLeave={(e)=>handleHover(e,false)}><GithubIcon/> GitHub Profile</a></div><div style={styles.keyContainer}><h2 style={styles.keyTitle}>Public PGP Key</h2><pre style={styles.keyBlock}><code>{pgpPublicKey}</code></pre><div style={styles.copyButtonContainer}><button style={styles.copyButton} onClick={handleCopy}>{copyButtonText}</button></div></div></div>);
};
