import { assert, assertEquals, assertStringIncludes } from '$std/assert/mod.ts';
import { render } from 'preact-render-to-string';
import ShopPage from './shop.tsx';
import { OWN_ITEMS } from '../data/shop.ts';

Deno.test('shop page carries a conspicuous affiliate disclosure', () => {
  const html = render(<ShopPage />);
  assertStringIncludes(html, 'affiliate');
});

Deno.test('affiliate disclosure appears above the catalog, not buried below it', () => {
  const html = render(<ShopPage />);
  const disclosureIndex = html.indexOf('affiliate');
  const catalogIndex = html.indexOf('Swann');
  assert(disclosureIndex !== -1, 'disclosure text ("affiliate") not found in rendered HTML');
  assert(catalogIndex !== -1, 'catalog item ("Swann") not found in rendered HTML');
  assert(
    disclosureIndex < catalogIndex,
    `expected the affiliate disclosure (index ${disclosureIndex}) to appear before the ` +
      `catalog (index ${catalogIndex}), but the catalog came first — the disclosure is no ` +
      'longer conspicuous/above the fold',
  );
});

Deno.test('shop page lists every Proust volume and de Botton', () => {
  const html = render(<ShopPage />);
  assertStringIncludes(html, 'Swann');
  assertStringIncludes(html, 'Finding Time Again');
  assertStringIncludes(html, 'How Proust Can Change Your Life');
});

Deno.test('each book offers both retailers', () => {
  const html = render(<ShopPage />);
  assertStringIncludes(html, 'penguinrandomhouse.com');
  assertStringIncludes(html, 'amazon.com');
});

Deno.test('tees link to Stripe and show the inclusive price', () => {
  const html = render(<ShopPage />);
  assertStringIncludes(html, 'https://buy.stripe.com/');
  // Assert both tees' prices, or a regression in either hides behind the other.
  assertStringIncludes(html, '$48');
  assertStringIncludes(html, '$49');
});

Deno.test('the Abhinava tee shows both views, described and responsive', () => {
  const html = render(<ShopPage />);
  assertStringIncludes(html, '/images/abhinava-tee-560.webp 560w');
  assertStringIncludes(html, '/images/abhinava-tee-951.webp 951w');
  assertStringIncludes(html, '/images/bhairava-yantra-560.webp 560w');
  assertStringIncludes(html, '/images/bhairava-yantra-1149.webp 1149w');
  assertStringIncludes(html, 'Front of a black t-shirt');
  assertStringIncludes(html, 'Back of the same t-shirt');
  // The views differ in aspect ratio, so each must carry its OWN intrinsic
  // height. Sharing one would reflow the column as the lazy images land.
  assertStringIncludes(html, 'height="640"');
  assertStringIncludes(html, 'height="667"');
});

Deno.test('a two-view item captions its views and spans the measure', () => {
  const html = render(<ShopPage />);
  assertStringIncludes(html, 'shop-item--gallery');
  assertStringIncludes(html, '<figcaption>front</figcaption>');
  assertStringIncludes(html, '<figcaption>back</figcaption>');
  // A gallery's slot is ~385px, not the 280px single-view column; the wrong
  // `sizes` makes the browser fetch a candidate for the wrong slot.
  assertStringIncludes(html, 'sizes="(max-width: 620px) 46vw, 385px"');
});

Deno.test('the tee discloses its lead time before the Buy button, not after', () => {
  const html = render(<ShopPage />);
  assertStringIncludes(html, '3–4 weeks lead time');
  assertStringIncludes(html, 'generated by Artificial Intelligence');
  assertStringIncludes(html, 'the vector files are in production');
  const caveat = html.indexOf('shop-caveat');
  const buy = html.indexOf('>Buy<', caveat);
  assert(caveat !== -1, 'caveat not rendered');
  assert(buy !== -1 && caveat < buy, 'the caveat must precede the Buy button it qualifies');
});

Deno.test('every view in the catalog renders exactly one figure, and no more', () => {
  const html = render(<ShopPage />);
  const declared = OWN_ITEMS.reduce((n, i) => n + (i.kind === 'own' ? (i.views?.length ?? 0) : 0), 0);
  const rendered = html.split('<figure').length - 1;
  assertEquals(
    rendered,
    declared,
    'figure count must equal the declared views — neither dropped nor invented',
  );
});

Deno.test('a view with no larger variant ships no srcset and is not upscaled', () => {
  const html = render(<ShopPage />);
  const img = html.slice(html.indexOf('/images/abhinavabsurd-213.webp') - 400);
  // A duplicate srcset candidate would only invite the browser to upscale a
  // 213px source into a 280px column.
  assert(!img.slice(0, 800).includes('srcset'), 'a view with no `wide` variant emitted a srcset');
  // The cap keeps that source sharp at its own size instead of soft at the
  // column's size.
  assertStringIncludes(html, 'max-width: 213px');
});
