// Generated by tools/compose-nav-rays.py; do not edit. Rerun it after any change there.

export interface NavRay {
  /** Tip of the ray, as a percentage of the fan box. */
  x: number;
  y: number;
  /** Degrees below horizontal; 162 is the leftmost ray, 18 the rightmost. */
  angle: number;
  /** Which way the label runs from the tip. */
  side: 'left' | 'right' | 'below';
}

export const NAV_RAYS: {
  width: number;
  height: number;
  markWidth: number;
  light: string;
  dark: string;
  rays: NavRay[];
} = {
  width: 600,
  height: 230,
  markWidth: 74,
  light: '/images/nav-rays-light.webp',
  dark: '/images/nav-rays-dark.webp',
  rays: [
    { x: 28.03, y: 35.69, angle: 162, side: 'left' },
    { x: 28.16, y: 65.26, angle: 138, side: 'left' },
    { x: 40.86, y: 66.53, angle: 114, side: 'left' },
    { x: 50.46, y: 70.94, angle: 90, side: 'below' },
    { x: 62.66, y: 81.82, angle: 66, side: 'right' },
    { x: 67.98, y: 54.06, angle: 42, side: 'right' },
    { x: 72.88, y: 35.69, angle: 18, side: 'right' },
  ],
};
