#!/usr/bin/env -S deno run --allow-read --allow-env
/**
 * Print the SQL that makes migrate.ts safe to run against this database.
 *
 * THE PROBLEM
 *
 * `_migrations` does not exist in production. migrate.ts has never run there --
 * every migration to date was applied by hand, and nothing recorded which. The
 * runner treats an empty tracking table as "nothing has been applied", so the
 * first `deno run migrate.ts` would replay all fifteen files from the top.
 *
 * Most are guarded with IF NOT EXISTS and would be harmless. Two are not:
 * 001_initial_schema.sql and 002_magic_links.sql are tombstones whose entire
 * body is DROP TABLE ... CASCADE. They exist to keep a retired plaintext-email
 * schema from coming back, and replaying them against a live database drops
 * tables by name and takes whatever CASCADE reaches with them.
 *
 * WHAT THIS DOES
 *
 * Emits the tracking table plus one INSERT per migration file already on disk,
 * marking them applied. After that the runner's diff is honest and only genuinely
 * new files run.
 *
 * It PRINTS rather than applies, for two reasons: the application role is
 * deliberately DML-only and cannot create a table anyway, and a script that
 * silently rewrites migration bookkeeping on production is exactly the kind of
 * thing that should be read by a person before it runs.
 *
 * USAGE
 *
 *   deno run --allow-read --allow-env scripts/bootstrap-migrations.ts
 *   deno run --allow-read --allow-env scripts/bootstrap-migrations.ts | psql "$OWNER_URL"
 *
 * Pass --exclude=014_profile_messaging.sql to leave a file unmarked so the
 * runner still applies it.
 */

const MIGRATIONS_DIR = './db/migrations';

function parseExcludes(): Set<string> {
  const out = new Set<string>();
  for (const arg of Deno.args) {
    if (arg.startsWith('--exclude=')) {
      for (const name of arg.slice('--exclude='.length).split(',')) {
        if (name.trim()) out.add(name.trim());
      }
    }
  }
  return out;
}

function sqlLiteral(value: string): string {
  return `'${value.replaceAll("'", "''")}'`;
}

async function main() {
  const excludes = parseExcludes();
  const names: string[] = [];

  for await (const entry of Deno.readDir(MIGRATIONS_DIR)) {
    if (entry.isFile && entry.name.endsWith('.sql')) names.push(entry.name);
  }

  // Same ordering migrate.ts uses, so the recorded set matches what it would
  // otherwise have tried to apply.
  names.sort();

  /*
   * An exclusion that matches nothing is a typo, and a silent one is dangerous
   * in exactly one direction: --exclude 001_initial_schmea.sql spells a file
   * that is not there, matches nothing, and the generated SQL then marks the
   * real 001_initial_schema.sql applied -- which is the DROP TABLE tombstone
   * this script exists to keep migrate.ts from replaying. Failing here costs a
   * retype; not failing costs the tables.
   */
  const unknown = [...excludes].filter((e) => !names.includes(e)).sort();
  if (unknown.length > 0) {
    console.error(`[bootstrap] No such migration: ${unknown.join(', ')}`);
    console.error(`[bootstrap] Known migrations: ${names.join(', ')}`);
    Deno.exit(2);
  }

  const marked = names.filter((n) => !excludes.has(n));
  const skipped = names.filter((n) => excludes.has(n));

  const lines: string[] = [
    '-- Generated by scripts/bootstrap-migrations.ts. Review before applying.',
    '--',
    '-- Marks every migration already on disk as applied, so migrate.ts cannot',
    '-- replay the DROP TABLE tombstones in 001_initial_schema.sql and',
    '-- 002_magic_links.sql against a live database.',
    '',
    'BEGIN;',
    '',
    'CREATE TABLE IF NOT EXISTS _migrations (',
    '  id SERIAL PRIMARY KEY,',
    '  name VARCHAR(255) NOT NULL UNIQUE,',
    '  applied_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()',
    ');',
    '',
  ];

  for (const name of marked) {
    lines.push(
      `INSERT INTO _migrations (name) VALUES (${sqlLiteral(name)}) ON CONFLICT (name) DO NOTHING;`,
    );
  }

  lines.push('', 'COMMIT;', '');

  if (skipped.length) {
    lines.push('-- Deliberately NOT marked, so migrate.ts still applies them:');
    for (const name of skipped) lines.push(`--   ${name}`);
    lines.push('');
  }

  lines.push(`-- ${marked.length} marked applied, ${skipped.length} left for the runner.`);

  console.log(lines.join('\n'));
}

if (import.meta.main) await main();
