/**
 * Copy the rendered tip jar into the static pages.
 *
 * public/contact.html and public/accessibility.html are plain files, not Fresh
 * routes, so they cannot render components/TipJar.tsx themselves. Rather than
 * hand-maintain a second copy of the addresses, this writes the component's own
 * markup between the TIP_JAR_START and TIP_JAR_END markers in each page.
 * tests/tip_jar_test.tsx fails if a page's copy differs from a fresh render.
 *
 * Run after editing data/tip-jar.ts:
 *   deno run --allow-read=public --allow-write=public scripts/sync-tip-jar.tsx
 */

import { render } from 'preact-render-to-string';
import TipJar from '../components/TipJar.tsx';

export const STATIC_PAGES = ['public/contact.html', 'public/accessibility.html'];
export const TIP_JAR_START = '<!-- tip-jar: generated by scripts/sync-tip-jar.tsx -->';
export const TIP_JAR_END = '<!-- /tip-jar -->';

export function renderTipJar(): string {
  return render(<TipJar />);
}

/** The markup currently between the markers, or null if a marker is missing. */
export function extractTipJar(html: string): string | null {
  const start = html.indexOf(TIP_JAR_START);
  const end = html.indexOf(TIP_JAR_END);
  if (start === -1 || end === -1 || end < start) return null;
  return html.slice(start + TIP_JAR_START.length, end);
}

export function spliceTipJar(html: string, snippet: string): string {
  const start = html.indexOf(TIP_JAR_START);
  const end = html.indexOf(TIP_JAR_END);
  if (start === -1 || end === -1 || end < start) throw new Error('tip-jar markers missing');
  return html.slice(0, start + TIP_JAR_START.length) + snippet + html.slice(end);
}

if (import.meta.main) {
  const snippet = renderTipJar();
  for (const page of STATIC_PAGES) {
    const html = await Deno.readTextFile(page);
    await Deno.writeTextFile(page, spliceTipJar(html, snippet));
    console.log(`synced ${page}`);
  }
}
