#!/usr/bin/env python3
"""Draw the nav's seven rays, after the Brooch wearable's boot screen.

The geometry is ~/Projects/ESP32/brooch/tools/compose_splash.py's, constants
copied verbatim: seven lens-shaped rays, a sharp core over a blurred glow,
fanning 18..162 degrees below horizontal off an ellipse around the spiral's
base stroke, the 2nd and 5th longer. Two things differ, both because a web nav
is not a 172x320 screen:

- The spiral is not drawn. The page already paints nav-irendu-372.webp; this
  draws only the rays, on transparent, positioned so the fan leaves the ௨'s base
  stroke when the mark is MARK_W wide and centred at the top of the box.
- Rays are longer (RAY_LEN): the Brooch's 17 px would end inside the spiral at
  this size, and each ray must reach its label.

Writes the rays at 3x for 3x displays (the rule nav-irendu-372.webp follows),
once per ground, and data/nav-rays.ts with each ray's tip as a percentage of the
box, so the links are positioned from the same numbers that drew the art.

    python3 tools/compose-nav-rays.py && deno fmt data/nav-rays.ts
"""
import hashlib
import math
from pathlib import Path

import numpy as np
from PIL import Image, ImageDraw, ImageFilter

ROOT = Path(__file__).resolve().parent.parent
W, H, SS = 600, 230, 3  # fan box in CSS px; drawn at 3x
MARK_W = 74  # the ௨ when open: 60% of its 124 px closed width
MARK_H = MARK_W * 252 / 372  # nav-irendu-372.webp is 372x252

# Brooch geometry, verbatim (compose_splash.py).
BASE_FX, BASE_FY = 0.537, 0.914
RAYS = 7
RAY_SPREAD = (18.0, 162.0)
BROOCH_SPIRAL_W = 141
RAY_ELLIPSE = (60.0, 14.0)
RAY_CORE_W, RAY_GLOW_W, RAY_GLOW_BLUR = 1.5, 4.0, 2.8
RAY_LEN_SCALE = [1.0, 1.35, 1.0, 1.0, 1.35, 1.0, 1.0]  # left to right

RAY_LEN = 110.0  # px at 1x

# (core, glow) per ground. Light: the wordmark's paper gold family; dark: the ink triad's gold.
VARIANTS = {
    "light": ((0x6E, 0x57, 0x00), (0xB8, 0x92, 0x0A)),
    "dark": ((0xFF, 0xF1, 0xA8), (0xFF, 0xD6, 0x00)),
}


def lens(x0, y0, x1, y1, w):
    """Pointed at both ends, widest at the middle (the Brooch's ray_polygon)."""
    mx, my = (x0 + x1) / 2, (y0 + y1) / 2
    dx, dy = x1 - x0, y1 - y0
    n = math.hypot(dx, dy)
    px, py = -dy / n * w / 2, dx / n * w / 2
    return [(x0, y0), (mx + px, my + py), (x1, y1), (mx - px, my - py)]


def geometry():
    """Per ray, left to right: (angle, start, tip) in 1x px."""
    cx = W / 2 + (BASE_FX - 0.5) * MARK_W
    cy = BASE_FY * MARK_H
    k = MARK_W / BROOCH_SPIRAL_W
    ex, ey = RAY_ELLIPSE[0] * k, RAY_ELLIPSE[1] * k
    out = []
    for i in range(RAYS):
        # Left to right: 162 degrees first, 18 last.
        a = RAY_SPREAD[1] - i * (RAY_SPREAD[1] - RAY_SPREAD[0]) / (RAYS - 1)
        c, s = math.cos(math.radians(a)), math.sin(math.radians(a))
        x0, y0 = cx + ex * c, cy + ey * s
        L = RAY_LEN * RAY_LEN_SCALE[i]
        out.append((a, (x0, y0), (x0 + L * c, y0 + L * s)))
    return out


def draw(core_rgb, glow_rgb, rays):
    core = Image.new("L", (W * SS, H * SS))
    glow = Image.new("L", (W * SS, H * SS))
    for _, (x0, y0), (x1, y1) in rays:
        pts = lambda w: [(x * SS, y * SS) for x, y in lens(x0, y0, x1, y1, w)]
        ImageDraw.Draw(core).polygon(pts(RAY_CORE_W), fill=255)
        ImageDraw.Draw(glow).polygon(pts(RAY_GLOW_W), fill=255)
    glow = glow.filter(ImageFilter.GaussianBlur(RAY_GLOW_BLUR * SS))
    c = np.asarray(core, float) / 255
    g = np.asarray(glow, float) / 255 * 0.75
    alpha = np.maximum(c, g)
    rgb = np.empty((H * SS, W * SS, 3))
    for ch in range(3):
        rgb[..., ch] = glow_rgb[ch] * (1 - c) + core_rgb[ch] * c
    rgba = np.dstack([rgb, alpha * 255]).clip(0, 255).astype(np.uint8)
    return Image.fromarray(rgba, "RGBA")


def side(a):
    return "left" if a > 100 else "right" if a < 80 else "below"


def main():
    rays = geometry()
    digests = {}
    for name, (core_rgb, glow_rgb) in VARIANTS.items():
        path = ROOT / f"public/images/nav-rays-{name}.webp"
        draw(core_rgb, glow_rgb, rays).save(path, "WEBP", lossless=True)
        # Recorded beside the tips, so a test can tell images and data apart after a partial regeneration.
        digests[name] = hashlib.sha256(path.read_bytes()).hexdigest()
    entries = ",\n".join(
        f"    {{ x: {x1 / W * 100:.2f}, y: {y1 / H * 100:.2f}, angle: {a:.0f}, side: '{side(a)}' }}"
        for a, _, (x1, y1) in rays
    )
    (ROOT / "data/nav-rays.ts").write_text(f"""// Generated by tools/compose-nav-rays.py; do not edit. Rerun it after any change there.

export interface NavRay {{
  /** Tip of the ray, as a percentage of the fan box. */
  x: number;
  y: number;
  /** Degrees below horizontal; 162 is the leftmost ray, 18 the rightmost. */
  angle: number;
  /** Which way the label runs from the tip. */
  side: 'left' | 'right' | 'below';
}}

export const NAV_RAYS: {{
  width: number;
  height: number;
  markWidth: number;
  light: string;
  dark: string;
  /** sha256 of each image, written with the tips so the two cannot drift apart. */
  sha256: {{ light: string; dark: string }};
  rays: NavRay[];
}} = {{
  width: {W},
  height: {H},
  markWidth: {MARK_W},
  light: '/images/nav-rays-light.webp',
  dark: '/images/nav-rays-dark.webp',
  sha256: {{ light: '{digests["light"]}', dark: '{digests["dark"]}' }},
  rays: [
{entries},
  ],
}};
""")
    print(f"wrote 2 images at {W * SS}x{H * SS} and data/nav-rays.ts")


if __name__ == "__main__":
    main()
